### ISSUE TITLE
Pick and Choose

### ISSUE THREAD

**Issue by YLee2121** [C-KLex/Phraends#5]
# Flask or Streamlit

Please determine one technology and empty the other one in the. 

I assume you guys will choose `streamlit` as the final framework. Therefore, please delete the redundant flask file ONLY. Don't adjust the folder path, I will personally rearrange the project layout after this issue is done! Then, the layout will be much cleaner and easier. 

## 💭Final Word

Open a PR to finish this task.😊

**Comment by viettran15** [comment]
The PR has opened and approved. We will move forward with Streamlit instead of Flask.
